version: "3.9"
services:
  db:
    image: postgres:15.1
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=more-reps
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
volumes:
  pgdata: