version: "3.9"
services:
  db:
    image: postgres:13.6
    command: postgres -c stats_temp_directory=/tmp
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=more-reps
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
volumes:
  pgdata: